/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front_end;

import back_end.User;
import java.awt.Color;

/**
 *
 * @author prasi
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Firstname_txt = new javax.swing.JTextField();
        login_btn = new javax.swing.JButton();
        signup_btn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Lastname_txt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Email_txt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Password_txt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        confirmPassword_txt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Username_txt = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel3.setText("Sign up");

        Firstname_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Firstname_txt.setForeground(new java.awt.Color(204, 204, 204));
        Firstname_txt.setText("Firstname");
        Firstname_txt.setToolTipText("");
        Firstname_txt.setBorder(null);
        Firstname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Firstname_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Firstname_txtFocusLost(evt);
            }
        });
        Firstname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Firstname_txtActionPerformed(evt);
            }
        });

        login_btn.setBackground(new java.awt.Color(51, 51, 51));
        login_btn.setForeground(new java.awt.Color(255, 255, 255));
        login_btn.setText("Login");
        login_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        signup_btn.setBackground(new java.awt.Color(0, 51, 204));
        signup_btn.setForeground(new java.awt.Color(255, 255, 255));
        signup_btn.setText("Signup");
        signup_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));

        Lastname_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Lastname_txt.setForeground(new java.awt.Color(204, 204, 204));
        Lastname_txt.setText("Lastname");
        Lastname_txt.setToolTipText("");
        Lastname_txt.setBorder(null);
        Lastname_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Lastname_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Lastname_txtFocusLost(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));

        Email_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Email_txt.setForeground(new java.awt.Color(204, 204, 204));
        Email_txt.setText("Email");
        Email_txt.setToolTipText("");
        Email_txt.setBorder(null);
        Email_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email_txtFocusLost(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));

        Password_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Password_txt.setForeground(new java.awt.Color(204, 204, 204));
        Password_txt.setText("Password atleast 4 character and 1 special letter");
        Password_txt.setToolTipText("");
        Password_txt.setBorder(null);
        Password_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_txtFocusLost(evt);
            }
        });
        Password_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_txtActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));

        confirmPassword_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        confirmPassword_txt.setForeground(new java.awt.Color(204, 204, 204));
        confirmPassword_txt.setText("Confirm Password");
        confirmPassword_txt.setToolTipText("");
        confirmPassword_txt.setBorder(null);
        confirmPassword_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPassword_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPassword_txtFocusLost(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));

        Username_txt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Username_txt.setForeground(new java.awt.Color(204, 204, 204));
        Username_txt.setText("Username");
        Username_txt.setToolTipText("");
        Username_txt.setBorder(null);
        Username_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Username_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Username_txtFocusLost(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator8.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(confirmPassword_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(login_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signup_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Firstname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lastname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(Email_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Firstname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lastname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmPassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Join with US");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Image");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(7, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        // TODO add your handling code here:
        String first = Firstname_txt.getText();
        String last = Lastname_txt.getText();
        String email1 = Email_txt.getText();
        String pass = Password_txt.getText();
        String rePass = confirmPassword_txt.getText();
        String user = Username_txt.getText();
        User obj = new User();
        obj.Setsignup(email1, pass, rePass, first, last, user, "Customer");
        Boolean check = obj.signup();
        
    }//GEN-LAST:event_signup_btnActionPerformed

    private void Firstname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Firstname_txtFocusGained
        // TODO add your handling code here:
        if (Firstname_txt.getText().equals("Firstname")) {
            Firstname_txt.setText("");
            Firstname_txt.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_Firstname_txtFocusGained

    private void Firstname_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Firstname_txtFocusLost
        // TODO add your handling code here:
        if(Firstname_txt.getText().equals("")){
            Firstname_txt.setText("Firstname");
            Firstname_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Firstname_txtFocusLost

    private void Lastname_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lastname_txtFocusGained
        // TODO add your handling code here:
        if(Lastname_txt.getText().equals("Lastname")){
            Lastname_txt.setText("");
            Lastname_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Lastname_txtFocusGained

    private void Lastname_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Lastname_txtFocusLost
        // TODO add your handling code here:
        if(Lastname_txt.getText().equals("")){
            Lastname_txt.setText("Lastname");
            Lastname_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Lastname_txtFocusLost

    private void Email_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_txtFocusGained
        // TODO add your handling code here:
        if(Email_txt.getText().equals("Email")){
            Email_txt.setText("");
            Email_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Email_txtFocusGained

    private void Email_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email_txtFocusLost
        // TODO add your handling code here:
        if(Email_txt.getText().equals("")){
            Email_txt.setText("Email");
            Email_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Email_txtFocusLost

    private void Password_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_txtFocusGained
        // TODO add your handling code here:
        if(Password_txt.getText().equals("Password atleast 4 character and 1 special letter")){
            Password_txt.setText("");
            Password_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Password_txtFocusGained

    private void Password_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_txtFocusLost
        // TODO add your handling code here:
        if(Password_txt.getText().equals("")){
            Password_txt.setText("Password atleast 4 character and 1 special letter");
            Password_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Password_txtFocusLost

    private void confirmPassword_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassword_txtFocusGained
        // TODO add your handling code here:
        if(confirmPassword_txt.getText().equals("Confirm Password")){
            confirmPassword_txt.setText("");
            confirmPassword_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_confirmPassword_txtFocusGained

    private void confirmPassword_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassword_txtFocusLost
        // TODO add your handling code here:
        if(confirmPassword_txt.getText().equals("")){
            confirmPassword_txt.setText("Confirm Password");
            confirmPassword_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_confirmPassword_txtFocusLost

    private void Username_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_txtFocusGained
        // TODO add your handling code here:
        if(Username_txt.getText().equals("Username")){
            Username_txt.setText("");
            Username_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Username_txtFocusGained

    private void Username_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_txtFocusLost
        // TODO add your handling code here:
        if(Username_txt.getText().equals("")){
            Username_txt.setText("Username");
            Username_txt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_Username_txtFocusLost

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        dispose();
        Login myLogin = new Login();
        myLogin.setTitle("Signup Page");
        myLogin.setVisible(true);
    }//GEN-LAST:event_login_btnActionPerformed

    private void Firstname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Firstname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Firstname_txtActionPerformed

    private void Password_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email_txt;
    private javax.swing.JTextField Firstname_txt;
    private javax.swing.JTextField Lastname_txt;
    private javax.swing.JTextField Password_txt;
    private javax.swing.JTextField Username_txt;
    private javax.swing.JTextField confirmPassword_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton login_btn;
    private javax.swing.JPanel panel;
    private javax.swing.JButton signup_btn;
    // End of variables declaration//GEN-END:variables
}
